### ISSUE TITLE
why use 200 as the number of fixed size?

### ISSUE THREAD

**Issue by xunhs** [eisenjulian/nlp_estimator_tutorial#1]
Hello, excuse me. In your blog-Classifying text with TensorFlow Estimators at the section of Loading the data, you set 200 as the number of fixed size of sequences. I found this sequences with a maximum of 2494 and minimum of 11, may i ask you why you set 200? Is there any references about that question?
Thank you very much.

**Comment by eisenjulian** [comment]
That's a good question, we mainly did that for performance reasons. All the models but the LSTM one handled larger sequences (~500) perfectly, but LSTMs became too slow. We didn't want to dig too much into that matter in the post since the idea was mostly to showcase how to set up the pipeline, but it's usually worth it to trim the long sentences to boost perf since a part of it can be enough for the task of sentiment analysis. However, I've seen research suggesting that taking the last part as opposed to the first can be better since people usually summarize their opinions at the end.
