### ISSUE TITLE
How to extend this logic for huge dataset

### ISSUE THREAD

**Issue by pathakrohit08** [eisenjulian/nlp_estimator_tutorial#4]
Thank you for this great example on input pipeline. 

`(x_train_variable, y_train), (x_test_variable, y_test) = imdb.load_data(num_words=vocab_size)`

I have a dataset that is 2GB in size. Unlike you I cannot load the whole data in memory. How can we modify this logic to include GB's dataset ?

**Comment by eisenjulian** [comment]
Hey @pathakrohit08 you have a number of approaches to tackle that problem. I would recommend looking deeper into the Datasets API. In this example, we are using `from_tensor_slices` to import samples from an in-memory numpy array, but if we don't really need all the data in memory since it can be streamed into each training batch.

Probably you can do well with `tf.data.TextLineDataset`. Check out the guide [here](https://www.tensorflow.org/guide/datasets#consuming_text_data) for more info.

Good luck!
